[StyleMain]
FontColor=#FontColor1#
FontFace=#FontFace1#
FontSize=#FontSize1#
StringAlign=CENTER
StringStyle=BOLD
AntiAlias=1
DynamicVariables=1

[StyleSub]
FontColor=#FontColor1#
FontFace=#FontFace1#
FontSize=#FontSize2#
StringAlign=CENTER
StringStyle=BOLD
AntiAlias=1
DynamicVariables=1

[StyleLabel]
W=90
H=14
FontColor=#FontColor1#
FontFace=#FontFace3#
FontSize=#FontSize6#
StringAlign=CENTER
StringStyle=BOLD
ClipString=1
AntiAlias=1
DynamicVariables=1

[StyleTag]
FontColor=#FontColor1#
FontFace=#FontFace4#
FontSize=#FontSize1#
StringAlign=LEFT
StringStyle=BOLD
AntiAlias=1
DynamicVariables=1

[StyleLine]
W=50
H=30
LineCount=1
LineColor=#FontColor2#,160
AntiAlias=1
DynamicVariables=1

[StyleHistogram]
X=r
Y=r
W=50
H=30
PrimaryColor=#FontColor2#,100
AntiAlias=1
DynamicVariables=1

[StyleM]
ImageAlpha=204
ImageTint=#FontColor2#
AntiAlias=1
DynamicVariables=1

[StyleB]
ImageAlpha=#Alpha#
ImageTint=#FontColor3#
AntiAlias=1
DynamicVariables=1